version: '2'

services:
  e2e-tests:
    build:
      context: ./
      dockerfile: ./e2e/Dockerfile
    image: microservicesdemo/e2e
    links:
      - microservicesdemo-oauth:gateway
  microservicesdemo-oauth:
    environment:
      NODE_ENV: test
  microservicesdemo-user:
    environment:
      NODE_ENV: test
